export const ShortTempProduct = [
  {
    id: 1,
    image: '이미지',
    contentTitle: '상품명',
    percent: 20,
    totalPrice: 10000,
    reviewScore: 4.8,
    totalReview: 1105,
  },
  {
    id: 2,
    image: '이미지',
    contentTitle: '상품명',
    percent: 20,
    totalPrice: 10000,
    reviewScore: 4.8,
    totalReview: 1105,
  },
  {
    id: 3,
    image: '이미지',
    contentTitle: '상품명',
    percent: 20,
    totalPrice: 10000,
    reviewScore: 4.8,
    totalReview: 1105,
  },
  {
    id: 4,
    image: '이미지',
    contentTitle: '상품명',
    percent: 20,
    totalPrice: 10000,
    reviewScore: 4.8,
    totalReview: 1105,
  },
];

export const TempProduct = [
  {
    id: 1,
    image: '이미지',
    contentTitle: '상품명',
    percent: 20,
    totalPrice: 10000,
    reviewScore: 4.8,
    totalReview: 1105,
  },
  {
    id: 2,
    image: '이미지',
    contentTitle: '상품명',
    percent: 20,
    totalPrice: 10000,
    reviewScore: 4.8,
    totalReview: 1105,
  },
  {
    id: 3,
    image: '이미지',
    contentTitle: '상품명',
    percent: 20,
    totalPrice: 10000,
    reviewScore: 4.8,
    totalReview: 1105,
  },
  {
    id: 4,
    image: '이미지',
    contentTitle: '상품명',
    percent: 20,
    totalPrice: 10000,
    reviewScore: 4.8,
    totalReview: 1105,
  },
  {
    id: 5,
    image: '이미지',
    contentTitle: '상품명',
    percent: 20,
    totalPrice: 10000,
    reviewScore: 4.8,
    totalReview: 1105,
  },
  {
    id: 6,
    image: '이미지',
    contentTitle: '상품명',
    percent: 20,
    totalPrice: 10000,
    reviewScore: 4.8,
    totalReview: 1105,
  },
  {
    id: 7,
    image: '이미지',
    contentTitle: '상품명',
    percent: 20,
    totalPrice: 10000,
    reviewScore: 4.8,
    totalReview: 1105,
  },
  {
    id: 8,
    image: '이미지',
    contentTitle: '상품명',
    percent: 20,
    totalPrice: 10000,
    reviewScore: 4.8,
    totalReview: 1105,
  },
];

export const OrderOptions: string[] = [
  '신상품순',
  '리뷰많은순',
  '낮은가격순',
  '높은가격순',
];

export const SizeOptions: string[] = ['Small', 'Medium', 'Large'];

export const CurrentPage = {
  fleshy: '다육이',
  cactus: '선인장',
  phalaenopsis: '호접란',
  scindapsus: '스킨답서스',
  palm: '야자목',
  petProduction: '키움용품',
};
