import React from 'react';
import styled from '@emotion/styled';
import Head from 'next/head';
import Header from '@components/Home/Header';
import Banner from '@components/Home/Banner';
import Category from '@components/Home/Category';
import ShopPrev from '@components/Home/ShopPrev';
import BestPlant from '@components/Home/BestPlant';
import BestReview from '@components/Home/BestReview';

const IndexPage = () => (
  <div>
    <Head>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Header/>
    <Banner/>
    <Category/>
    <ShopPrev/>
    <BestPlant/>
    <BestReview/>
  </div>
);

export default IndexPage;
