import React from 'react';
import styled from '@emotion/styled';
import Head from 'next/head';
import Header from '@components/Home/Header';
import Banner from '@components/Home/Banner';

const IndexPage = () => (
  <div>
    <Head>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Header/>
    <Banner/>
  </div>
);

export default IndexPage;
